package org.crypttech.modexp.testgenerator;

import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

import org.crypttech.modexp.testgenerator.format.GeneratorC;
import org.crypttech.modexp.testgenerator.format.ModExpTestFormater;

public class TestGenerator {
	public static void main(String[] argv) throws Exception {
		System.out.println("Generating modexp test values.");

		List<TestVector> vectors = new ArrayList<TestVector>();
		vectors.addAll(TestGeneratorBasic.getTestVectors());
			try (GeneratorC genC = new GeneratorC("../model/c/src/autogenerated_tests.c")) {
				ArrayList<ModExpTestFormater> generators = new ArrayList<ModExpTestFormater>();
				generators.add(genC);

				emitTests(vectors, generators);
			}
		
	}

	private static void emitTests(List<TestVector> vectors,
			List<ModExpTestFormater> generators) {
		for (ModExpTestFormater generator : generators)
			for (TestVector vector : vectors)
				generator.format(vector);
	}
}
