#include <stdio.h>
#include <stdlib.h>
#include "montgomery_array.h"
#include "bignum_uint32_t.h"
void autogenerated_BASIC_M4962768465676381896(void) {
  printf("=== autogenerated_BASIC_M4962768465676381896 ===\n");
  uint32_t X[] = { 0x00000001, 0x946473e1 };
  uint32_t E[] = { 0x00000001, 0x0e85e74f };
  uint32_t M[] = { 0x00000001, 0x70754797 };
  uint32_t expected[] = { 0x00000000, 0x7761ed4f };
  uint32_t Z[] = { 0x00000000, 0x00000000 };
  mod_exp_array(2, X, E, M, Z);
  assertArrayEquals(2, expected, Z);
}
void autogenerated_BASIC_8982867242010371843(void) {
  printf("=== autogenerated_BASIC_8982867242010371843 ===\n");
  uint32_t X[] = { 0x00000001, 0x6eb4ac2d };
  uint32_t E[] = { 0x00000001, 0xbb200e41 };
  uint32_t M[] = { 0x00000001, 0x27347dc3 };
  uint32_t expected[] = { 0x00000000, 0x87d16204 };
  uint32_t Z[] = { 0x00000000, 0x00000000 };
  mod_exp_array(2, X, E, M, Z);
  assertArrayEquals(2, expected, Z);
}
void autogenerated_BASIC_5090788032873075449(void) {
  printf("=== autogenerated_BASIC_5090788032873075449 ===\n");
  uint32_t X[] = { 0x00000001, 0x9e504a03 };
  uint32_t E[] = { 0x00000001, 0x9bc057ef };
  uint32_t M[] = { 0x00000001, 0xc8b53fe5 };
  uint32_t expected[] = { 0x00000001, 0xc1a6494c };
  uint32_t Z[] = { 0x00000000, 0x00000000 };
  mod_exp_array(2, X, E, M, Z);
  assertArrayEquals(2, expected, Z);
}
void autogenerated_BASIC_8448510918869952728(void) {
  printf("=== autogenerated_BASIC_8448510918869952728 ===\n");
  uint32_t X[] = { 0x00000001, 0x73f7b309 };
  uint32_t E[] = { 0x00000001, 0x91c10f7f };
  uint32_t M[] = { 0x00000001, 0x4be322c9 };
  uint32_t expected[] = { 0x00000000, 0x9a155286 };
  uint32_t Z[] = { 0x00000000, 0x00000000 };
  mod_exp_array(2, X, E, M, Z);
  assertArrayEquals(2, expected, Z);
}
void autogenerated_BASIC_4036237668019554146(void) {
  printf("=== autogenerated_BASIC_4036237668019554146 ===\n");
  uint32_t X[] = { 0x00000001, 0xd0f3961d };
  uint32_t E[] = { 0x00000001, 0xcdbc9c9d };
  uint32_t M[] = { 0x00000001, 0x30367d5b };
  uint32_t expected[] = { 0x00000001, 0x15a9c15d };
  uint32_t Z[] = { 0x00000000, 0x00000000 };
  mod_exp_array(2, X, E, M, Z);
  assertArrayEquals(2, expected, Z);
}
void autogenerated_BASIC_M8925041444689012509(void) {
  printf("=== autogenerated_BASIC_M8925041444689012509 ===\n");
  uint32_t X[] = { 0x00000001, 0x34130e17 };
  uint32_t E[] = { 0x00000001, 0xf45e52c9 };
  uint32_t M[] = { 0x00000001, 0x9cb5c68d };
  uint32_t expected[] = { 0x00000000, 0x7c129d37 };
  uint32_t Z[] = { 0x00000000, 0x00000000 };
  mod_exp_array(2, X, E, M, Z);
  assertArrayEquals(2, expected, Z);
}
void autogenerated_BASIC_M5713608137760059379(void) {
  printf("=== autogenerated_BASIC_M5713608137760059379 ===\n");
  uint32_t X[] = { 0x00000001, 0x77505dbd };
  uint32_t E[] = { 0x00000001, 0xdb808627 };
  uint32_t M[] = { 0x00000001, 0xad1fed09 };
  uint32_t expected[] = { 0x00000001, 0x842cd733 };
  uint32_t Z[] = { 0x00000000, 0x00000000 };
  mod_exp_array(2, X, E, M, Z);
  assertArrayEquals(2, expected, Z);
}
void autogenerated_BASIC_6816968587684568101(void) {
  printf("=== autogenerated_BASIC_6816968587684568101 ===\n");
  uint32_t X[] = { 0x00000001, 0x3272b6ef };
  uint32_t E[] = { 0x00000001, 0x2cb6c09b };
  uint32_t M[] = { 0x00000001, 0xefbc64fd };
  uint32_t expected[] = { 0x00000001, 0x59c3b603 };
  uint32_t Z[] = { 0x00000000, 0x00000000 };
  mod_exp_array(2, X, E, M, Z);
  assertArrayEquals(2, expected, Z);
}
void autogenerated_BASIC_4168013900853404774(void) {
  printf("=== autogenerated_BASIC_4168013900853404774 ===\n");
  uint32_t X[] = { 0x00000001, 0x3c20bbcf };
  uint32_t E[] = { 0x00000001, 0xa495d8ab };
  uint32_t M[] = { 0x00000001, 0x75ddb9ef };
  uint32_t expected[] = { 0x00000001, 0x1413eac7 };
  uint32_t Z[] = { 0x00000000, 0x00000000 };
  mod_exp_array(2, X, E, M, Z);
  assertArrayEquals(2, expected, Z);
}
void autogenerated_BASIC_M8394821325674331878(void) {
  printf("=== autogenerated_BASIC_M8394821325674331878 ===\n");
  uint32_t X[] = { 0x00000001, 0x93d3d0d3 };
  uint32_t E[] = { 0x00000001, 0x43c2dfef };
  uint32_t M[] = { 0x00000001, 0x7443cbf1 };
  uint32_t expected[] = { 0x00000000, 0xc2eda7c3 };
  uint32_t Z[] = { 0x00000000, 0x00000000 };
  mod_exp_array(2, X, E, M, Z);
  assertArrayEquals(2, expected, Z);
}
void autogenerated_BASIC_M2919828800172604435(void) {
  printf("=== autogenerated_BASIC_M2919828800172604435 ===\n");
  uint32_t X[] = { 0x3d746ec5 };
  uint32_t E[] = { 0x3f7ea6d5 };
  uint32_t M[] = { 0x29b6675f };
  uint32_t expected[] = { 0x040c43d8 };
  uint32_t Z[] = { 0x00000000 };
  mod_exp_array(1, X, E, M, Z);
  assertArrayEquals(1, expected, Z);
}
void autogenerated_BASIC_4770912732078070597(void) {
  printf("=== autogenerated_BASIC_4770912732078070597 ===\n");
  uint32_t X[] = { 0x200c0f45 };
  uint32_t E[] = { 0x24774bab };
  uint32_t M[] = { 0x234ca073 };
  uint32_t expected[] = { 0x14505436 };
  uint32_t Z[] = { 0x00000000 };
  mod_exp_array(1, X, E, M, Z);
  assertArrayEquals(1, expected, Z);
}
void autogenerated_BASIC_3593487472385409519(void) {
  printf("=== autogenerated_BASIC_3593487472385409519 ===\n");
  uint32_t X[] = { 0x248819d1 };
  uint32_t E[] = { 0x2ad2b6ed };
  uint32_t M[] = { 0x269cc6bf };
  uint32_t expected[] = { 0x0f09d466 };
  uint32_t Z[] = { 0x00000000 };
  mod_exp_array(1, X, E, M, Z);
  assertArrayEquals(1, expected, Z);
}
void autogenerated_BASIC_4981749054780354961(void) {
  printf("=== autogenerated_BASIC_4981749054780354961 ===\n");
  uint32_t X[] = { 0x27bec4e7 };
  uint32_t E[] = { 0x36fe540f };
  uint32_t M[] = { 0x25a46d61 };
  uint32_t expected[] = { 0x0bab2269 };
  uint32_t Z[] = { 0x00000000 };
  mod_exp_array(1, X, E, M, Z);
  assertArrayEquals(1, expected, Z);
}
void autogenerated_BASIC_7702189670289360961(void) {
  printf("=== autogenerated_BASIC_7702189670289360961 ===\n");
  uint32_t X[] = { 0x302def29 };
  uint32_t E[] = { 0x25b9c233 };
  uint32_t M[] = { 0x33af5461 };
  uint32_t expected[] = { 0x0229dc08 };
  uint32_t Z[] = { 0x00000000 };
  mod_exp_array(1, X, E, M, Z);
  assertArrayEquals(1, expected, Z);
}
void autogenerated_BASIC_M5169634701858105792(void) {
  printf("=== autogenerated_BASIC_M5169634701858105792 ===\n");
  uint32_t X[] = { 0x240d8cf5 };
  uint32_t E[] = { 0x2a6a7381 };
  uint32_t M[] = { 0x3471d1e9 };
  uint32_t expected[] = { 0x244dec19 };
  uint32_t Z[] = { 0x00000000 };
  mod_exp_array(1, X, E, M, Z);
  assertArrayEquals(1, expected, Z);
}
void autogenerated_BASIC_6469444563916025786(void) {
  printf("=== autogenerated_BASIC_6469444563916025786 ===\n");
  uint32_t X[] = { 0x3cc9270b };
  uint32_t E[] = { 0x27858fdd };
  uint32_t M[] = { 0x21e65001 };
  uint32_t expected[] = { 0x17200d8c };
  uint32_t Z[] = { 0x00000000 };
  mod_exp_array(1, X, E, M, Z);
  assertArrayEquals(1, expected, Z);
}
void autogenerated_BASIC_M2453278165832221565(void) {
  printf("=== autogenerated_BASIC_M2453278165832221565 ===\n");
  uint32_t X[] = { 0x30ca6ceb };
  uint32_t E[] = { 0x212c387b };
  uint32_t M[] = { 0x2e07a7bb };
  uint32_t expected[] = { 0x0fc15a1f };
  uint32_t Z[] = { 0x00000000 };
  mod_exp_array(1, X, E, M, Z);
  assertArrayEquals(1, expected, Z);
}
void autogenerated_BASIC_M1847183855567461116(void) {
  printf("=== autogenerated_BASIC_M1847183855567461116 ===\n");
  uint32_t X[] = { 0x3d02c5a1 };
  uint32_t E[] = { 0x35f12b45 };
  uint32_t M[] = { 0x32f0b03f };
  uint32_t expected[] = { 0x2340f96f };
  uint32_t Z[] = { 0x00000000 };
  mod_exp_array(1, X, E, M, Z);
  assertArrayEquals(1, expected, Z);
}
void autogenerated_BASIC_M7037130911981370263(void) {
  printf("=== autogenerated_BASIC_M7037130911981370263 ===\n");
  uint32_t X[] = { 0x2692d1cd };
  uint32_t E[] = { 0x3b21ef8d };
  uint32_t M[] = { 0x2042c76d };
  uint32_t expected[] = { 0x1b753aea };
  uint32_t Z[] = { 0x00000000 };
  mod_exp_array(1, X, E, M, Z);
  assertArrayEquals(1, expected, Z);
}
void autogenerated_tests(void) {
  autogenerated_BASIC_M4962768465676381896();
  autogenerated_BASIC_8982867242010371843();
  autogenerated_BASIC_5090788032873075449();
  autogenerated_BASIC_8448510918869952728();
  autogenerated_BASIC_4036237668019554146();
  autogenerated_BASIC_M8925041444689012509();
  autogenerated_BASIC_M5713608137760059379();
  autogenerated_BASIC_6816968587684568101();
  autogenerated_BASIC_4168013900853404774();
  autogenerated_BASIC_M8394821325674331878();
  autogenerated_BASIC_M2919828800172604435();
  autogenerated_BASIC_4770912732078070597();
  autogenerated_BASIC_3593487472385409519();
  autogenerated_BASIC_4981749054780354961();
  autogenerated_BASIC_7702189670289360961();
  autogenerated_BASIC_M5169634701858105792();
  autogenerated_BASIC_6469444563916025786();
  autogenerated_BASIC_M2453278165832221565();
  autogenerated_BASIC_M1847183855567461116();
  autogenerated_BASIC_M7037130911981370263();

}
