#include <stdio.h>
#include <stdlib.h>
#include "montgomery_array.h"
#include "bignum_uint32_t.h"
void autogenerated_BASIC_M4962768465676381896(void) {
  printf("=== autogenerated_BASIC_M4962768465676381896 ===\n");
  uint32_t X[] = { 0x00000001, 0x946473e1 };
  uint32_t E[] = { 0x00000001, 0x0e85e74f };
  uint32_t M[] = { 0x00000001, 0x70754797 };
  uint32_t expected[] = { 0x00000000, 0x7761ed4f };
  uint32_t Z[] = { 0x00000000, 0x00000000 };
  mod_exp_array(2, X, E, M, Z);
  assertArrayEquals(2, expected, Z);
}
void autogenerated_BASIC_8982867242010371843(void) {
  printf("=== autogenerated_BASIC_8982867242010371843 ===\n");
  uint32_t X[] = { 0x00000001, 0x6eb4ac2d };
  uint32_t E[] = { 0x00000001, 0xbb200e41 };
  uint32_t M[] = { 0x00000001, 0x27347dc3 };
  uint32_t expected[] = { 0x00000000, 0x87d16204 };
  uint32_t Z[] = { 0x00000000, 0x00000000 };
  mod_exp_array(2, X, E, M, Z);
  assertArrayEquals(2, expected, Z);
}
void autogenerated_BASIC_5090788032873075449(void) {
  printf("=== autogenerated_BASIC_5090788032873075449 ===\n");
  uint32_t X[] = { 0x00000001, 0x9e504a03 };
  uint32_t E[] = { 0x00000001, 0x9bc057ef };
  uint32_t M[] = { 0x00000001, 0xc8b53fe5 };
  uint32_t expected[] = { 0x00000001, 0xc1a6494c };
  uint32_t Z[] = { 0x00000000, 0x00000000 };
  mod_exp_array(2, X, E, M, Z);
  assertArrayEquals(2, expected, Z);
}
void autogenerated_BASIC_8448510918869952728(void) {
  printf("=== autogenerated_BASIC_8448510918869952728 ===\n");
  uint32_t X[] = { 0x00000001, 0x73f7b309 };
  uint32_t E[] = { 0x00000001, 0x91c10f7f };
  uint32_t M[] = { 0x00000001, 0x4be322c9 };
  uint32_t expected[] = { 0x00000000, 0x9a155286 };
  uint32_t Z[] = { 0x00000000, 0x00000000 };
  mod_exp_array(2, X, E, M, Z);
  assertArrayEquals(2, expected, Z);
}
void autogenerated_BASIC_4036237668019554146(void) {
  printf("=== autogenerated_BASIC_4036237668019554146 ===\n");
  uint32_t X[] = { 0x00000001, 0xd0f3961d };
  uint32_t E[] = { 0x00000001, 0xcdbc9c9d };
  uint32_t M[] = { 0x00000001, 0x30367d5b };
  uint32_t expected[] = { 0x00000001, 0x15a9c15d };
  uint32_t Z[] = { 0x00000000, 0x00000000 };
  mod_exp_array(2, X, E, M, Z);
  assertArrayEquals(2, expected, Z);
}
void autogenerated_BASIC_M8925041444689012509(void) {
  printf("=== autogenerated_BASIC_M8925041444689012509 ===\n");
  uint32_t X[] = { 0x00000001, 0x34130e17 };
  uint32_t E[] = { 0x00000001, 0xf45e52c9 };
  uint32_t M[] = { 0x00000001, 0x9cb5c68d };
  uint32_t expected[] = { 0x00000000, 0x7c129d37 };
  uint32_t Z[] = { 0x00000000, 0x00000000 };
  mod_exp_array(2, X, E, M, Z);
  assertArrayEquals(2, expected, Z);
}
void autogenerated_BASIC_M5713608137760059379(void) {
  printf("=== autogenerated_BASIC_M5713608137760059379 ===\n");
  uint32_t X[] = { 0x00000001, 0x77505dbd };
  uint32_t E[] = { 0x00000001, 0xdb808627 };
  uint32_t M[] = { 0x00000001, 0xad1fed09 };
  uint32_t expected[] = { 0x00000001, 0x842cd733 };
  uint32_t Z[] = { 0x00000000, 0x00000000 };
  mod_exp_array(2, X, E, M, Z);
  assertArrayEquals(2, expected, Z);
}
void autogenerated_BASIC_6816968587684568101(void) {
  printf("=== autogenerated_BASIC_6816968587684568101 ===\n");
  uint32_t X[] = { 0x00000001, 0x3272b6ef };
  uint32_t E[] = { 0x00000001, 0x2cb6c09b };
  uint32_t M[] = { 0x00000001, 0xefbc64fd };
  uint32_t expected[] = { 0x00000001, 0x59c3b603 };
  uint32_t Z[] = { 0x00000000, 0x00000000 };
  mod_exp_array(2, X, E, M, Z);
  assertArrayEquals(2, expected, Z);
}
void autogenerated_BASIC_4168013900853404774(void) {
  printf("=== autogenerated_BASIC_4168013900853404774 ===\n");
  uint32_t X[] = { 0x00000001, 0x3c20bbcf };
  uint32_t E[] = { 0x00000001, 0xa495d8ab };
  uint32_t M[] = { 0x00000001, 0x75ddb9ef };
  uint32_t expected[] = { 0x00000001, 0x1413eac7 };
  uint32_t Z[] = { 0x00000000, 0x00000000 };
  mod_exp_array(2, X, E, M, Z);
  assertArrayEquals(2, expected, Z);
}
void autogenerated_BASIC_M8394821325674331878(void) {
  printf("=== autogenerated_BASIC_M8394821325674331878 ===\n");
  uint32_t X[] = { 0x00000001, 0x93d3d0d3 };
  uint32_t E[] = { 0x00000001, 0x43c2dfef };
  uint32_t M[] = { 0x00000001, 0x7443cbf1 };
  uint32_t expected[] = { 0x00000000, 0xc2eda7c3 };
  uint32_t Z[] = { 0x00000000, 0x00000000 };
  mod_exp_array(2, X, E, M, Z);
  assertArrayEquals(2, expected, Z);
}
void autogenerated_BASIC_M2919828800172604435(void) {
  printf("=== autogenerated_BASIC_M2919828800172604435 ===\n");
  uint32_t X[] = { 0x3d746ec5 };
  uint32_t E[] = { 0x3f7ea6d5 };
  uint32_t M[] = { 0x29b6675f };
  uint32_t expected[] = { 0x040c43d8 };
  uint32_t Z[] = { 0x00000000 };
  mod_exp_array(1, X, E, M, Z);
  assertArrayEquals(1, expected, Z);
}
void autogenerated_BASIC_4770912732078070597(void) {
  printf("=== autogenerated_BASIC_4770912732078070597 ===\n");
  uint32_t X[] = { 0x200c0f45 };
  uint32_t E[] = { 0x24774bab };
  uint32_t M[] = { 0x234ca073 };
  uint32_t expected[] = { 0x14505436 };
  uint32_t Z[] = { 0x00000000 };
  mod_exp_array(1, X, E, M, Z);
  assertArrayEquals(1, expected, Z);
}
void autogenerated_BASIC_3593487472385409519(void) {
  printf("=== autogenerated_BASIC_3593487472385409519 ===\n");
  uint32_t X[] = { 0x248819d1 };
  uint32_t E[] = { 0x2ad2b6ed };
  uint32_t M[] = { 0x269cc6bf };
  uint32_t expected[] = { 0x0f09d466 };
  uint32_t Z[] = { 0x00000000 };
  mod_exp_array(1, X, E, M, Z);
  assertArrayEquals(1, expected, Z);
}
void autogenerated_BASIC_4981749054780354961(void) {
  printf("=== autogenerated_BASIC_4981749054780354961 ===\n");
  uint32_t X[] = { 0x27bec4e7 };
  uint32_t E[] = { 0x36fe540f };
  uint32_t M[] = { 0x25a46d61 };
  uint32_t expected[] = { 0x0bab2269 };
  uint32_t Z[] = { 0x00000000 };
  mod_exp_array(1, X, E, M, Z);
  assertArrayEquals(1, expected, Z);
}
void autogenerated_BASIC_7702189670289360961(void) {
  printf("=== autogenerated_BASIC_7702189670289360961 ===\n");
  uint32_t X[] = { 0x302def29 };
  uint32_t E[] = { 0x25b9c233 };
  uint32_t M[] = { 0x33af5461 };
  uint32_t expected[] = { 0x0229dc08 };
  uint32_t Z[] = { 0x00000000 };
  mod_exp_array(1, X, E, M, Z);
  assertArrayEquals(1, expected, Z);
}
void autogenerated_BASIC_M5169634701858105792(void) {
  printf("=== autogenerated_BASIC_M5169634701858105792 ===\n");
  uint32_t X[] = { 0x240d8cf5 };
  uint32_t E[] = { 0x2a6a7381 };
  uint32_t M[] = { 0x3471d1e9 };
  uint32_t expected[] = { 0x244dec19 };
  uint32_t Z[] = { 0x00000000 };
  mod_exp_array(1, X, E, M, Z);
  assertArrayEquals(1, expected, Z);
}
void autogenerated_BASIC_6469444563916025786(void) {
  printf("=== autogenerated_BASIC_6469444563916025786 ===\n");
  uint32_t X[] = { 0x3cc9270b };
  uint32_t E[] = { 0x27858fdd };
  uint32_t M[] = { 0x21e65001 };
  uint32_t expected[] = { 0x17200d8c };
  uint32_t Z[] = { 0x00000000 };
  mod_exp_array(1, X, E, M, Z);
  assertArrayEquals(1, expected, Z);
}
void autogenerated_BASIC_M2453278165832221565(void) {
  printf("=== autogenerated_BASIC_M2453278165832221565 ===\n");
  uint32_t X[] = { 0x30ca6ceb };
  uint32_t E[] = { 0x212c387b };
  uint32_t M[] = { 0x2e07a7bb };
  uint32_t expected[] = { 0x0fc15a1f };
  uint32_t Z[] = { 0x00000000 };
  mod_exp_array(1, X, E, M, Z);
  assertArrayEquals(1, expected, Z);
}
void autogenerated_BASIC_M1847183855567461116(void) {
  printf("=== autogenerated_BASIC_M1847183855567461116 ===\n");
  uint32_t X[] = { 0x3d02c5a1 };
  uint32_t E[] = { 0x35f12b45 };
  uint32_t M[] = { 0x32f0b03f };
  uint32_t expected[] = { 0x2340f96f };
  uint32_t Z[] = { 0x00000000 };
  mod_exp_array(1, X, E, M, Z);
  assertArrayEquals(1, expected, Z);
}
void autogenerated_BASIC_M7037130911981370263(void) {
  printf("=== autogenerated_BASIC_M7037130911981370263 ===\n");
  uint32_t X[] = { 0x2692d1cd };
  uint32_t E[] = { 0x3b21ef8d };
  uint32_t M[] = { 0x2042c76d };
  uint32_t expected[] = { 0x1b753aea };
  uint32_t Z[] = { 0x00000000 };
  mod_exp_array(1, X, E, M, Z);
  assertArrayEquals(1, expected, Z);
}
void autogenerated_BASIC_5073338267670769216(void) {
  printf("=== autogenerated_BASIC_5073338267670769216 ===\n");
  uint32_t X[] = { 0x3028983f, 0xdc9bdc25, 0xa3fdfeda, 0x283f4463 };
  uint32_t E[] = { 0x29493211, 0xc4252db0, 0x7775443d, 0x13e1d929 };
  uint32_t M[] = { 0x2fb9ba2f, 0xa485d5f7, 0x3c6652c9, 0x670fdbfd };
  uint32_t expected[] = { 0x2f45cdd6, 0x23f0e6f2, 0xaa4bd5d8, 0x6297da06 };
  uint32_t Z[] = { 0x00000000, 0x00000000, 0x00000000, 0x00000000 };
  mod_exp_array(4, X, E, M, Z);
  assertArrayEquals(4, expected, Z);
}
void autogenerated_BASIC_M1841989679506188752(void) {
  printf("=== autogenerated_BASIC_M1841989679506188752 ===\n");
  uint32_t X[] = { 0x29462882, 0x12caa2d5, 0xb80e1c66, 0x1006807f };
  uint32_t E[] = { 0x3285c343, 0x2acbcb0f, 0x4d023228, 0x2ecc73db };
  uint32_t M[] = { 0x267d2f2e, 0x51c216a7, 0xda752ead, 0x48d22d89 };
  uint32_t expected[] = { 0x0ddc404d, 0x91600596, 0x7425a8d8, 0xa066ca56 };
  uint32_t Z[] = { 0x00000000, 0x00000000, 0x00000000, 0x00000000 };
  mod_exp_array(4, X, E, M, Z);
  assertArrayEquals(4, expected, Z);
}
void autogenerated_BASIC_M3339729654500648482(void) {
  printf("=== autogenerated_BASIC_M3339729654500648482 ===\n");
  uint32_t X[] = { 0x2963efb9, 0xc6f5d260, 0xa2d0fe74, 0x49726b57 };
  uint32_t E[] = { 0x2f55c103, 0xbace4bf1, 0x2ab9fac2, 0x30aec7d3 };
  uint32_t M[] = { 0x376cf9ae, 0xd9e988e8, 0xbd995f5c, 0xdeec42f5 };
  uint32_t expected[] = { 0x0ce8cff7, 0x9f564e2c, 0x1b61e3d9, 0x717db9ef };
  uint32_t Z[] = { 0x00000000, 0x00000000, 0x00000000, 0x00000000 };
  mod_exp_array(4, X, E, M, Z);
  assertArrayEquals(4, expected, Z);
}
void autogenerated_BASIC_M6837928193394880512(void) {
  printf("=== autogenerated_BASIC_M6837928193394880512 ===\n");
  uint32_t X[] = { 0x2a9283cc, 0x5999f49d, 0xf8cf6ab2, 0x5f47bf25 };
  uint32_t E[] = { 0x2c7564a0, 0x2d1fcda1, 0x2825318a, 0xae23c271 };
  uint32_t M[] = { 0x32b892f9, 0x096c5ada, 0x43918370, 0x8398c7e3 };
  uint32_t expected[] = { 0x27cf8839, 0x94004d82, 0xa0d69d86, 0x3f61a929 };
  uint32_t Z[] = { 0x00000000, 0x00000000, 0x00000000, 0x00000000 };
  mod_exp_array(4, X, E, M, Z);
  assertArrayEquals(4, expected, Z);
}
void autogenerated_BASIC_M7333111649825079555(void) {
  printf("=== autogenerated_BASIC_M7333111649825079555 ===\n");
  uint32_t X[] = { 0x246fa2ec, 0x405f234d, 0x39b93e77, 0xf16bcc91 };
  uint32_t E[] = { 0x2807eb7a, 0x646df633, 0xeaa95a21, 0x85252adf };
  uint32_t M[] = { 0x2cdd3307, 0x782e5711, 0x584f179b, 0x011087df };
  uint32_t expected[] = { 0x02d6e42e, 0x46e2d304, 0x435170c1, 0x9f344f83 };
  uint32_t Z[] = { 0x00000000, 0x00000000, 0x00000000, 0x00000000 };
  mod_exp_array(4, X, E, M, Z);
  assertArrayEquals(4, expected, Z);
}
void autogenerated_BASIC_480186175131589607(void) {
  printf("=== autogenerated_BASIC_480186175131589607 ===\n");
  uint32_t X[] = { 0x300a5cf7, 0x269f6369, 0x02e025cb, 0xaf16fcfd };
  uint32_t E[] = { 0x2cc4b1c0, 0x9205a8b4, 0xbc130ee2, 0x923f1f3f };
  uint32_t M[] = { 0x2cd376d5, 0xd9e3b080, 0x2533288a, 0xd4b9bb37 };
  uint32_t expected[] = { 0x0ae9c475, 0xf4fb4c63, 0xcf2c4f56, 0x902eba0c };
  uint32_t Z[] = { 0x00000000, 0x00000000, 0x00000000, 0x00000000 };
  mod_exp_array(4, X, E, M, Z);
  assertArrayEquals(4, expected, Z);
}
void autogenerated_BASIC_M5239159917778665002(void) {
  printf("=== autogenerated_BASIC_M5239159917778665002 ===\n");
  uint32_t X[] = { 0x3eaed5af, 0xa287db7e, 0x4ff07fee, 0x9bbda80b };
  uint32_t E[] = { 0x3c077d49, 0xf3a131ab, 0x6289042a, 0xc15083cb };
  uint32_t M[] = { 0x344b8538, 0xcf4f2576, 0xd28c1c52, 0xc83a8199 };
  uint32_t expected[] = { 0x15028046, 0x5c12d235, 0x7580fd1b, 0x6bc76b24 };
  uint32_t Z[] = { 0x00000000, 0x00000000, 0x00000000, 0x00000000 };
  mod_exp_array(4, X, E, M, Z);
  assertArrayEquals(4, expected, Z);
}
void autogenerated_BASIC_228752064885223799(void) {
  printf("=== autogenerated_BASIC_228752064885223799 ===\n");
  uint32_t X[] = { 0x3904d7ab, 0x13937a4f, 0x926856d1, 0x6bdda621 };
  uint32_t E[] = { 0x3d360083, 0xa50eaf0e, 0xffce2df2, 0xb1f51cef };
  uint32_t M[] = { 0x2d32376f, 0x205555b3, 0x2c9daf8c, 0xe2b7cf81 };
  uint32_t expected[] = { 0x08836692, 0xe6398828, 0x1eeccd57, 0x2c231153 };
  uint32_t Z[] = { 0x00000000, 0x00000000, 0x00000000, 0x00000000 };
  mod_exp_array(4, X, E, M, Z);
  assertArrayEquals(4, expected, Z);
}
void autogenerated_BASIC_856940511857911599(void) {
  printf("=== autogenerated_BASIC_856940511857911599 ===\n");
  uint32_t X[] = { 0x23e80223, 0x52b700ee, 0x6cb8a294, 0x47c6fac9 };
  uint32_t E[] = { 0x253cebdb, 0xcc78dcb4, 0x925682b3, 0x490c424b };
  uint32_t M[] = { 0x2f2885eb, 0x67987cee, 0x717298bd, 0x7a1baf7b };
  uint32_t expected[] = { 0x2bb0b86c, 0xc854652b, 0x2b2bce27, 0xd2595a8e };
  uint32_t Z[] = { 0x00000000, 0x00000000, 0x00000000, 0x00000000 };
  mod_exp_array(4, X, E, M, Z);
  assertArrayEquals(4, expected, Z);
}
void autogenerated_BASIC_M6501553661140603953(void) {
  printf("=== autogenerated_BASIC_M6501553661140603953 ===\n");
  uint32_t X[] = { 0x287e9711, 0x4d346dab, 0x3ff5e6da, 0xa93edebd };
  uint32_t E[] = { 0x3658192a, 0x4b5fac3f, 0x9a78bc81, 0x5ac8c667 };
  uint32_t M[] = { 0x238cd95d, 0x298ee5e1, 0x320323da, 0x0a46ec21 };
  uint32_t expected[] = { 0x0415fef6, 0x5fc81702, 0x8be83fd4, 0x4c7fbf24 };
  uint32_t Z[] = { 0x00000000, 0x00000000, 0x00000000, 0x00000000 };
  mod_exp_array(4, X, E, M, Z);
  assertArrayEquals(4, expected, Z);
}
void autogenerated_tests(void) {
  autogenerated_BASIC_M4962768465676381896();
  autogenerated_BASIC_8982867242010371843();
  autogenerated_BASIC_5090788032873075449();
  autogenerated_BASIC_8448510918869952728();
  autogenerated_BASIC_4036237668019554146();
  autogenerated_BASIC_M8925041444689012509();
  autogenerated_BASIC_M5713608137760059379();
  autogenerated_BASIC_6816968587684568101();
  autogenerated_BASIC_4168013900853404774();
  autogenerated_BASIC_M8394821325674331878();
  autogenerated_BASIC_M2919828800172604435();
  autogenerated_BASIC_4770912732078070597();
  autogenerated_BASIC_3593487472385409519();
  autogenerated_BASIC_4981749054780354961();
  autogenerated_BASIC_7702189670289360961();
  autogenerated_BASIC_M5169634701858105792();
  autogenerated_BASIC_6469444563916025786();
  autogenerated_BASIC_M2453278165832221565();
  autogenerated_BASIC_M1847183855567461116();
  autogenerated_BASIC_M7037130911981370263();
  autogenerated_BASIC_5073338267670769216();
  autogenerated_BASIC_M1841989679506188752();
  autogenerated_BASIC_M3339729654500648482();
  autogenerated_BASIC_M6837928193394880512();
  autogenerated_BASIC_M7333111649825079555();
  autogenerated_BASIC_480186175131589607();
  autogenerated_BASIC_M5239159917778665002();
  autogenerated_BASIC_228752064885223799();
  autogenerated_BASIC_856940511857911599();
  autogenerated_BASIC_M6501553661140603953();

}
