################################################################################
# Automatically-generated file. Do not edit!
################################################################################

CC = clang
CC_OPT = -O2
CC_FLAGS = -g3 -pedantic -pedantic-errors -Wall -Wextra -Werror -Wconversion -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)"

# Add inputs and outputs from these tool invocations to the build variables
C_SRCS += \
../src/ModExpTestBench.c \
../src/simple_tests.c \
../src/autogenerated_tests.c \
../src/bignum_uint32_t.c \
../src/montgomery_array.c \
../src/montgomery_array_test.c

OBJS += \
./src/ModExpTestBench.o \
./src/simple_tests.o \
./src/autogenerated_tests.o \
./src/bignum_uint32_t.o \
./src/montgomery_array.o \
./src/montgomery_array_test.o

C_DEPS += \
./src/ModExpTestBench.d \
./src/simple_tests.d \
./src/autogenerated_tests.d \
./src/bignum_uint32_t.d \
./src/montgomery_array.d \
./src/montgomery_array_test.d


# Each subdirectory must supply rules for building sources it contributes
src/%.o: ../src/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: clang C Compiler'
	$(CC) $(CC_OPT) $(CC_FLAGS) -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '
